spring:
  application:
    name: mailer
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/events?authSource=admin&authMechanism=SCRAM-SHA-1
  cloud:
    consul:
      discovery:
        hostname: localhost
        port: 8500
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        serviceName: service-${spring.application.name}
        healthCheckPath: ${management.server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ???
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 0